### ISSUE TITLE
The demo project seems not work correctly 

### ISSUE THREAD

**Issue by jessejiang0214** [AndreiMisiukevich/ContextMenu#1]
I just download the project and launch it in iOS and Android simulator.
In iOS simulator, it cannot be dragged 
![simulator screen shot - iphone 8 - 2018-07-10 at 08 33 34](https://user-images.githubusercontent.com/4516628/42479411-2876ac02-841c-11e8-8dfa-5743450ab8fc.png)
In Android, the Layout is incorrect
![screenshot_1531175604](https://user-images.githubusercontent.com/4516628/42479426-31b83966-841c-11e8-9401-44e65f231f3c.png)

**Comment by AndreiMisiukevich** [comment]
Thank you for quick response

What iOS simulator do you use?

**Comment by AndreiMisiukevich** [comment]
Ok, got it on iPhone 6s simulator
Try please iPhone 5s.. i will fix this issue =)

**Comment by AndreiMisiukevich** [comment]
@jessejiang0214 try it now please)

**Comment by AndreiMisiukevich** [comment]
Reopen this issue if you face with any troubles. Now it should work well

I added fix =)
