### ISSUE TITLE
ContextMenu scroll consumes a viewcell with scrollview inside

### ISSUE THREAD

**Issue by ShahmanTeh** [AndreiMisiukevich/ContextMenu#11]
setting up ContextMenu for a custom viewcell that has a scrollview inside works, however the scrollview has consumed the ViewCell's child scrollview itself.

**Comment by AndreiMisiukevich** [comment]
Hi @ShahmanTeh 
Yes..

Any ideas, how to solve it?

**Comment by AndreiMisiukevich** [comment]
i presume it is constraint of using this plugin (you can't use scroll inside your cell)

**Comment by AndreiMisiukevich** [comment]
i think it's bad UX practice (using ScrollView inside cells, so, unfortunately, i am not keen to support such case. Sorry)
