### ISSUE TITLE
Swipe event

### ISSUE THREAD

**Issue by sesitosvdx** [AndreiMisiukevich/ContextMenu#12]
Hi @AndreiMisiukevich,

Great plugin! I'm trying to change the text of < and > before and after a swipe. 

![image](https://user-images.githubusercontent.com/47418326/52409577-27c37680-2ad6-11e9-8c83-3367158ed8bf.png)

Is there anyway I can detect swiping so that I can bind that text to change between > and < ?

**Comment by AndreiMisiukevich** [comment]
Hi, you can use these events https://github.com/AndreiMisiukevich/ContextMenu/blob/master/ContextMenu/BaseActionViewCell.cs#L21-L27

**Comment by AndreiMisiukevich** [comment]
Is it helpful?

**Comment by sesitosvdx** [comment]
I guess it is, but sorry, I don't know how to implement them...

Could you provide and example?

**Comment by AndreiMisiukevich** [comment]
@sesitosvdx create your own view cell and inherit from SideActionBarCell
```charp
public class YourCell : SideActionBarCell
{
    public YourCell()
    {
            ContextMenuOpened += (c) => {    {CHANGE IMAGE LOGIC}   };
            ContextMenuClosed += (c) => {    {CHANGE IMAGE BACK LOGIC}   };
    }
}
```

**Comment by sesitosvdx** [comment]
Ok. Will try.

Thank you! <3
