### ISSUE TITLE
Exception on OnScrollToRequestedNew with Xamarin Forms 3.6.0.264807

### ISSUE THREAD

**Issue by rocktool27** [AndreiMisiukevich/ContextMenu#14]
Hi @AndreiMisiukevich I I upgraded to Xamarin Forms 3.6.0.264807 and compiled an apk release and the following exception came out 

03-20 22:13:33.680 12386 12386 I MonoDroid: UNHANDLED EXCEPTION:
03-20 22:13:33.720 12386 12386 I MonoDroid: Java.Lang.RuntimeException: int[] offset=0 length=4352 dst.length=1
03-20 22:13:33.720 12386 12386 I MonoDroid:   at Java.Interop.JniEnvironment+Arrays.SetIntArrayRegion (Java.Interop.JniObjectReference array, System.Int32 start, System.Int32 length, System.Int32* buffer) [0x0003f] in <6ff1b57bf204413890283db4db9f885b>:0 
03-20 22:13:33.720 12386 12386 I MonoDroid:   at Android.Runtime.JNIEnv.CopyArray (System.Int32[] src, System.IntPtr dest) [0x0002d] in <031883663a0e408897a6f567fca5881a>:0 
03-20 22:13:33.720 12386 12386 I MonoDroid:   at Android.Runtime.JNIEnv.NewArray (System.Int32[] array) [0x0001a] in <031883663a0e408897a6f567fca5881a>:0 
03-20 22:13:33.720 12386 12386 I MonoDroid:   at Android.Support.V4.Widget.NestedScrollView.DispatchNestedPreScroll (System.Int32 dx, System.Int32 dy, System.Int32[] consumed, System.Int32[] offsetInWindow, System.Int32 type) [0x00000] in <33eeedd1164f4f24b77d150d7e62ecfb>:0 
03-20 22:13:33.720 12386 12386 I MonoDroid:   at ContextMenu.Droid.ContextMenuScrollViewRenderer+<OnScrollToRequestedNew>d__12.MoveNext () [0x00241] in <dd17584a330f48e885bee97c675cf9f1>:0 
03-20 22:13:33.720 12386 12386 I MonoDroid: --- End of stack trace from previous location where exception was thrown ---

**Comment by rocktool27** [comment]
Hi again, I updated the component with the same XF version and gave me this error

Edit: It's with apk release

Unexpected task error "LinkAssemblies".
Mono.Linker.MarkException: Error processing method: 'System.Void ContextMenu.Droid.ContextMenuScrollViewRenderer/<>c__DisplayClass12_0::<OnScrollToRequestedNew>b__1()' in assembly: 'ContextMenu.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.V4.Widget.NestedScrollView::SmoothScrollTo(System.Int32,System.Int32)
   en Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   en Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   en Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   en Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   en Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   en Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Mono.Linker.Steps.MarkStep.ProcessQueue()
   en Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   en Mono.Linker.Steps.MarkStep.Process()
   en MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   en Mono.Linker.Pipeline.Process(LinkContext context)
   en MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   en Xamarin.Android.Tasks.LinkAssemblies.Execute()
   en Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   en Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Xpinnit.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2129

**Comment by AndreiMisiukevich** [comment]
Does anybody want to debug this case?)

**Comment by rocktool27** [comment]
If it's helpful, I use Xamarin.Android.Support components version 27.0.2.1
And my target is 8.1 Oreo

**Comment by AndreiMisiukevich** [comment]
check new version

**Comment by thaihuydang** [comment]
Hi, I have had the same error with version 2.0.
I used X.F 3.6.0.220655
====================
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void ContextMenu.Droid.ContextMenuScrollViewRenderer/<>c__DisplayClass12_0::<OnScrollToRequestedNew>b__1()' in assembly: 'ContextMenu.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.V4.Widget.NestedScrollView::SmoothScrollTo(System.Int32,System.Int32)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by AndreiMisiukevich** [comment]
@rocktool27 have you read Readme file yet ?

Did you initialized plugin correctly and updated Xamarin andoid packages to 28.x.x version?

**Comment by thaihuydang** [comment]
yes, I read the Readme file and did what in this file. I also update android packages to 28.x.x version

**Comment by AndreiMisiukevich** [comment]
@thaihuydang can you try to replicate this issue on my sample?
