### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [AndreiMisiukevich/ContextMenu#16]
Your plugin great, please support UWP thank!

**Comment by AndreiMisiukevich** [comment]
Hi) would you like to contribute it?)

**Comment by nguyenthanhliemfc** [comment]
@AndreiMisiukevich Great, I hope I can help!

**Comment by AndreiMisiukevich** [comment]
@nguyenthanhliemfc please look at https://github.com/AndreiMisiukevich/ContextMenu/blob/master/ContextMenu.iOS/ContextMenuScrollViewRenderer.cs

How i implemented it for iOS
Need to do something like this

**Comment by AndreiMisiukevich** [comment]
Still help wanted :)

**Comment by nguyenthanhliemfc** [comment]
@alexmartinezm I have try to add ContextMenuSample.UWP. It's crash on app start up!

**Comment by AndreiMisiukevich** [comment]
@nguyenthanhliemfc weird

**Comment by Orgbrat** [comment]
Like your plugin but cannot use it until you have UWP support...  Let us know when you get UWP working.

**Comment by AndreiMisiukevich** [comment]
@Orgbrat would you like to contribute a little code for uwp ?

**Comment by Orgbrat** [comment]
Sorry, I am deep into a new Xamarin Forms app and have my time obligated

**Comment by AndreiMisiukevich** [comment]
You should use XF SwipeView :)
