### ISSUE TITLE
resources in sample at wrong location

### ISSUE THREAD

**Issue by Zure1** [AndreiMisiukevich/ContextMenu#17]
When downloading your project, these resources are missing in the sample:

ContextMenuSample/ContextMenuSample.iOS/Resources/phila.png
ContextMenuSample/ContextMenuSample.iOS/Resources/nets.png
ContextMenuSample/ContextMenuSample.iOS/Resources/bulls.png

Same for Android drawable folder.

For some reason, they are located in this folder: C:\Users\Zure1\Downloads\ContextMenu-master\ContextMenu-master\files

**Comment by Zure1** [comment]
I think something just didn't work with the linking. I copied the repo again and it's working now.

**Comment by AndreiMisiukevich** [comment]
@Zure1 haha) cool) anyway thanks for feedback
