### ISSUE TITLE
Add OuterLeftContent and OuterRightContent

### ISSUE THREAD

**Issue by Zure1** [AndreiMisiukevich/ContextMenu#19]
Add properties "OuterLeftContent" and "OuterRightContent" to BaseActionViewCell. Setting a view to one of this property adds this view to the left/right side of the cell. When swiping the cell, the OuterContent will not be swiped.

This is useful for example if one needs to add any kind of progress bar to the ListView which should not be swiped.

**Comment by Zure1** [comment]
See PR #21

**Comment by AndreiMisiukevich** [comment]
@Zure1 i release views (so you can combine layout as you wish)
