### ISSUE TITLE
Example with code

### ISSUE THREAD

**Issue by acaliaro** [AndreiMisiukevich/ContextMenu#2]
Hi @AndreiMisiukevich 
could you translate your XAML example in CSHARP?

Thanks
Alessandro

**Comment by AndreiMisiukevich** [comment]
Hi.
Sure, I will do it and let you know
Thanks for feedback

**Comment by acaliaro** [comment]
wow, you are fast. Thanks!

**Comment by AndreiMisiukevich** [comment]
Readme is updated =)

**Comment by acaliaro** [comment]
Thanks I take a look
