### ISSUE TITLE
Add ContextMenu from left side

### ISSUE THREAD

**Issue by Zure1** [AndreiMisiukevich/ContextMenu#20]
Currently, it's only possible to swipe from right to left to reveal a ContextMenu. There should be a possibility to swipe from left to right too and reveal a ContextMenu on the left side of the cell.

**Comment by TechBlackSparrow** [comment]
@AndreiMisiukevich 

**In Right To Left Approach:**
Each Row is a Scrollview, in that two views are added.

- 1st view is Content View
- 2nd view is Context Menu
	Since, you are adding Context Menu as 2nd view, it's hidden always. when touch happens, you are changing the ScrollX position of the Scrollview to reveal/dismiss the context Menu **- its working fine.**

**But, Left to Right Approach:**
We have to interchange the view order,

- 1st View is should be Context Menu.
- 2nd view is should be Content View. 

	When SetContextMenu method calls, contextview is creating and it's visible on the left side as default. We have to change the ScrollView's ScrollX value to ContextMenu's width, then only its getting hide.
	When user scrolls, list view rows are recreating, context menu is visible as default, we have to scroll the scrollview every-time to hide the context menu. It’s glitching the animation. **- is this understanding correct, any solution for this issue?**

**i think this below is the best approach :**
	Instead using Scrollview and adding two view inside that.
	Inside a frame layout, stack context menu in back side and top of it add Content Menu.When touch happens, change the Content Menu’s Margin position, to reveals/hide the background context menu.

Any suggestions on this.

**Comment by Zure1** [comment]
@TechBlackSparrow this works, I've done this in my private project. Personally, I don't like the visual effect of it though because the context menu won't move like it does now.

**Comment by TechBlackSparrow** [comment]
@Zure1  Left To Right context menu, you have done in your private project. is it working on Android also without any animation issue?.

**Comment by Zure1** [comment]
No, it did have animation issues. I opened a stackoverflow question [here](https://stackoverflow.com/questions/53203857/listview-cell-translation-manipulation-affects-other-cells) about my problem. But someone linked to this project in the comments and I'm trying to add this feature to this problem right now.

I'm sure you could fix this issue tho, someone already answered on my question on stackoverflow how it could be possible. But there are other issues with my project which caused me to use ContextMenu project instead.

**Comment by AndreiMisiukevich** [comment]
Here is guideline, how to achieve "left menu"
there is nothing difficult - just set Rotation = 180 to ContextMenuView and to menu's main view and context view.

![image](https://user-images.githubusercontent.com/10124814/58128162-a7a5c480-7c1f-11e9-9422-9c2678335d83.png)

![q](https://user-images.githubusercontent.com/10124814/58128309-fd7a6c80-7c1f-11e9-9c2a-bffc7f141cbc.gif)

**Comment by Zure1** [comment]
Good idea, but is it possible like this to have ContextMenu from left **and** right side on the same item?

**Comment by AndreiMisiukevich** [comment]
@Zure1 hmm
Not sure, cuz we use scrollview.

But... Hm, but we can try )
