### ISSUE TITLE
SideActionBar-consecutive swipes and clicks on listview items do not auto close listview items

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [AndreiMisiukevich/ContextMenu#23]
SideActionBar-consecutive swipes and clicks on listview items do not auto close listview items

**Comment by AndreiMisiukevich** [comment]
@rajamaheshwarsingh hi
Yes, unfortunately it won't be fixed. 
Developer should decide himself, when contextmenu should be closed.
Sorry
