### ISSUE TITLE
Enhancement: Enable the use of a viewcell as content

### ISSUE THREAD

**Issue by Daan298261** [AndreiMisiukevich/ContextMenu#25]
It would be very useful to be able to use a viewcell as main content.

**Comment by AndreiMisiukevich** [comment]
@DaanTacoSchool hi
Sorry, could you please explain what do you mean?

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/ContextMenu/issues/18

Allow to use it outside of ListView ?

**Comment by Daan298261** [comment]
Like this
```
 <ListView.ItemTemplate>
                        <DataTemplate x:DataType="models:ExpenseReport"  >
                            <context:SideActionBarCell>
                                <context:SideActionBarCell.Content>                    
<--custom viewcell in c# here like this:>
<local:QueuedExpenseCardViewCell  ExpenseItem="{Binding .}"  ImageSource="{Binding AttachmentPath}" Appearing="Cell_OnAppearing" >
                                </context:SideActionBarCell.Content>
                                 <context:SideActionBarCell.ContextTemplate >
                                     <DataTemplate>
                                     <some other buttons>
                                 
                               </DataTemplate>
                                </context:SideActionBarCell.ContextTemplate>
                            </context:SideActionBarCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
```

except since the sideactionbar is derived from a baseActionCell this is not possible.

**Comment by AndreiMisiukevich** [comment]
@DaanTacoSchool hmm, just copy content of that cell and set to **Content**

ViewCell inside ViewCell - it's something strange

**Comment by Daan298261** [comment]
Yes, i originally used a viewcell because there is a lot of complex code linked to the cell and its visual cues. by making a custom cell it was easier to keep track of things. (among some other reasons).

Can i derive my viewcell from the sideactionbarcell?

**Comment by AndreiMisiukevich** [comment]
> Yes, i originally used a viewcell because there is a lot of complex code linked to the cell and its visual cues. by making a custom cell it was easier to keep track of things. (among some other reasons).
> 
> Can i derive my viewcell from the sideactionbarcell?

why you don't want to create ContentView as separate xaml file?

**Comment by Daan298261** [comment]
Because most of it is in c# and not in xml :)

**Comment by AndreiMisiukevich** [comment]
@DaanTacoSchool copy it to xaml.cs of ContentView
