### ISSUE TITLE
Suggestion - A way to notify users about this functionality

### ISSUE THREAD

**Issue by matteopiccioni** [AndreiMisiukevich/ContextMenu#26]
Hello,
when the users go in the page with the list of items (only the first time?), 
would be nice to have a way to show a short and strategic self-moving of the cells, 
to inform the users that is possible to slide the cells
Thanks for your work!

**Comment by AndreiMisiukevich** [comment]
@matteopiccioni yes, you can achieve it very easily

just call 
```csharp
await contextMenu.ScrollToAsync(40, 0, true); 
contextMenu.ForceClose(true);
```

**Comment by CodeOfDarkness** [comment]
Hi Andrei Misiukevich,
I'm relative new to Xamarin and have a question.

How can I access a single element of ContextMenu when used in a ListView to trigger that ScrollToAsync on a single View only?

**Comment by AndreiMisiukevich** [comment]
@CodeOfDarkness i think you should do it through code

**Comment by CodeOfDarkness** [comment]
I don't know how to access it by code

**Comment by AndreiMisiukevich** [comment]
@CodeOfDarkness if you use ListView, you may create custom ViewCell e.g.

**Comment by CodeOfDarkness** [comment]
@AndreiMisiukevich Ok thanks for your quick help 👍
