### ISSUE TITLE
Swipe doesn't work when cell's width is smaller than the listView's

### ISSUE THREAD

**Issue by andreipro1002** [AndreiMisiukevich/ContextMenu#28]
Hey,
As title says, in my application I need the view cell to have a smaller width than the list view's, and in this case the swipe doesn't work anymore. Is this a bug or intended? Is there a work around to achieve this?

Thanks in advance,
Andrei

**Comment by AndreiMisiukevich** [comment]
@andreipro hi,

It's neither bug, nor feature. some kind of restriction :)

i think, you may try to bind WidthRequest of your .View to menu's Width

Like in sample, but without converter, and source should be ```context:SideContextMenuView```

https://github.com/AndreiMisiukevich/ContextMenu/blob/master/ContextMenuSample/ContextMenuSample/Pages/SideMenuPage.xaml#L32-L36

**Comment by andreipro1002** [comment]
@AndreiMisiukevich Hey, thanks for the fast reply. I forgot to mention that I am using SideActionBarCell, the SideActionBarCell.Content will have the "width = ListView.Width - 40" where 40 represents the left + right margins for the view cell. And in SideActionBarCell.ContextTemplate I have 2 buttons with 120 width each. On the content I'm using WidthRequest to get that value written above, but as I said the swipe doesn't work in this case. Do I need to do something else? Thanks

**Comment by AndreiMisiukevich** [comment]
@andreipro can you provide small sample project?

**Comment by andreipro1002** [comment]
@AndreiMisiukevich Hey, in the end I took another approach in fixing this, you can close the topic. Thanks :)
