### ISSUE TITLE
Swipe to delete

### ISSUE THREAD

**Issue by acaliaro** [AndreiMisiukevich/ContextMenu#3]
Hi @andreimisiukevich

It should be fantastic to have a swipe to delete functionality...

**Comment by AndreiMisiukevich** [comment]
cool idea, i will think about it.
Just add new cell type with such feature

**Comment by AndreiMisiukevich** [comment]
@acaliaro hi) I haven't forgot. I will try to find time for development today-tomorrow)

**Comment by AndreiMisiukevich** [comment]
@acaliaro hi) could you check the sample? I added new type of cell with such feature
