### ISSUE TITLE
how to avoid swiping two listview items at once

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [AndreiMisiukevich/ContextMenu#30]
how to avoid swiping two listview items at once

**Comment by AndreiMisiukevich** [comment]
What is your case?

***IsAutoCloseEnabled = true*** by default. So you try to open new menu item, prev will be closed

**Comment by rajamaheshwarsingh** [comment]
if we use two fingers, one on each list view item and try to  swipe both the items simultaneously, then both the items are swiped. In Ideal case, user should be able to swipe only one item not both.

**Comment by AndreiMisiukevich** [comment]
@rajamaheshwarsingh got it.

Hmm, i think you will have to try to work around with IsEnabled ... (change it on status changing)

not sure about it

**Comment by rajamaheshwarsingh** [comment]
I need help on "where can I check for two views are opened at the same time, so that I can validate code for only one view to be opened at any time"

**Comment by AndreiMisiukevich** [comment]
@rajamaheshwarsingh it's just ScrollView
Maybe you can try to make all your non-selected views IsEnabled = false.
Not sure how to resolve it

**Comment by AndreiMisiukevich** [comment]
public event Action<BaseContextMenuView> TouchStarted;
        public event Action<BaseContextMenuView> TouchEnded;

On start -- forbid to touch any other views, on end -- allow again
