### ISSUE TITLE
activity indicator

### ISSUE THREAD

**Issue by stefanvesely** [AndreiMisiukevich/ContextMenu#32]
Good Day sir, thank you for the amazing piece of work, I have one issue that i have encountered, once i add an activity indicator to the form, the list only shows if you tap the content, it's weird, have you heard of this issue? or experienced it?

**Comment by AndreiMisiukevich** [comment]
weird) do you mind to provide a sample?

**Comment by stefanvesely** [comment]
unfortunately not, I am working with a private sql database and web interface that is also private and has a bunch of sensitive information on, what i can do it provide the code for the view model and the form.
`<TabbedPage  xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AndroidFueledV1"
             xmlns:context="clr-namespace:ContextMenu.Views;assembly=ContextMenu"
             x:Class="AndroidFueledV1.MainPage">

    <ContentPage Title="Home" Icon="Home.png" BackgroundColor="#0F2169">
        <ContentPage.Content>
            <StackLayout Padding="10">
                <StackLayout>
                    <Label Text="Username :" TextColor="White"></Label>
                    <Entry IsSpellCheckEnabled="false" Placeholder="Username" BackgroundColor="#004c99"
                           Text="{Binding SUser}" TextColor="White"  PlaceholderColor="White" />
                    <Label TextColor="White" Text="Password :"></Label>
                    <Entry TextColor="White" IsPassword="true" IsSpellCheckEnabled="false"
                           BackgroundColor="#004c99" Placeholder="Password" PlaceholderColor="White" Text="{Binding SPass}" />
                </StackLayout>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="1*" />
                        <ColumnDefinition Width="1*" />
                        <ColumnDefinition Width="1*" />
                    </Grid.ColumnDefinitions>

                    <Button CornerRadius="10" Command="{Binding LoginCommand}" Grid.Column="1" Text="Log In"></Button>
                </Grid>
                <StackLayout>
                    <Label  TextColor="White" Text="Remember Me"></Label>
                    <Switch BackgroundColor="#004c99" OnColor="White"  HorizontalOptions="Start" IsToggled="{Binding RememberMe}" />
                   
                </StackLayout>
                <Label  TextColor="White" Text="Branch :" />
                <Picker IsEnabled="{Binding IsenabledBRANCH}" BackgroundColor="#004c99" TextColor="White" ItemsSource="{Binding BranchList}" Title="Select a Branch" SelectedItem="{Binding SBranch}" />
                <ActivityIndicator IsRunning="{Binding IsBusy}"/>
            </StackLayout>
           
        </ContentPage.Content>
       
    </ContentPage>
    <ContentPage Title="Overview" Icon="Overview.png" BackgroundColor="#0F2169">
        <ContentPage.Content>
            <StackLayout Rotation="90" Margin="-160,45,0,0">
                <Grid  BackgroundColor="DarkRed" >
                    <Grid.RowDefinitions>
                        <RowDefinition Height="50"></RowDefinition>
                    </Grid.RowDefinitions>

                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="75" ></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                    </Grid.ColumnDefinitions>

                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="0" Grid.Row="0"  Text="Tank:" FontAttributes="Bold" />
                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="1" Grid.Row="0"  Text="Fuel:" FontAttributes="Bold" />
                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="2" Grid.Row="0"  Text="Capacity:" FontAttributes="Bold" />
                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="3" Grid.Row="0"  Text="Current:" FontAttributes="Bold" />
                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="4" Grid.Row="0"  Text="AVGSales:" FontAttributes="Bold" />
                    <Label TextColor="White" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Grid.Column="5" Grid.Row="0"  Text="Rundry (days):" FontAttributes="Bold" />
                </Grid>
                <Grid HorizontalOptions="StartAndExpand" VerticalOptions="StartAndExpand">
                    <Grid.RowDefinitions>
                        <RowDefinition></RowDefinition>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                        <ColumnDefinition Width="75"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <ListView Grid.Column="0" ItemsSource="{Binding LSTankName}" >
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                    <ListView Grid.Column="1" ItemsSource="{Binding LSProduct}" >
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                    <ListView Grid.Column="2" ItemsSource="{Binding LSCapacity}">
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                    <ListView Grid.Column="3" ItemsSource="{Binding LSCurrentAmount}">
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                    <ListView Grid.Column="4" ItemsSource="{Binding LSAvgMovement}">
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                    <ListView Grid.Column="5" ItemsSource="{Binding LSRunDryDays}">
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <TextCell Text="{Binding .}" TextColor="White"/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                </Grid>
            </StackLayout>
        </ContentPage.Content>
    </ContentPage>
    <ContentPage x:Name="NewsTab" Title="News" Icon="News.png" BackgroundColor="#0F2169">
        <ContentPage.Content>
            <StackLayout Padding="10">
                <CollectionView x:Name="CollectionView" ItemsSource="{Binding CleanList}">
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <context:SideContextMenuView IsAutoCloseEnabled="true">
                                <context:SideContextMenuView.View>
                                    <Frame WidthRequest="270" HeightRequest="100"
                                           BackgroundColor="#1a6de0" Margin="15,5" Padding="20" CornerRadius="10">
                                        <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" Spacing="10">
                                            <Label Text="{Binding Newsitem}" FontAttributes="Bold" TextColor="White" LineBreakMode="WordWrap" MaxLines="5" />
                                        </StackLayout>
                                    </Frame>
                                </context:SideContextMenuView.View>
                                <context:SideContextMenuView.ContextTemplate>
                                    <DataTemplate>
                                        <Frame Margin="0, 5" Padding="0" CornerRadius="10" IsClippedToBounds="true" BackgroundColor="#004c99">
                                            <StackLayout Padding="10, 5" Orientation="Horizontal" Spacing="10" Margin="0, 5">
                                                <ImageButton BackgroundColor="#004c99"  Command="{Binding BindingContext.DeleteCommand, Source={x:Reference CollectionView}}" CommandParameter="{Binding .}"
                                                             Source="delete.png" HeightRequest="60" WidthRequest="60" VerticalOptions="CenterAndExpand" HorizontalOptions="EndAndExpand" />
                                                <ImageButton BackgroundColor="#004c99" Command="{Binding BindingContext.NewsViewCommand, Source={x:Reference CollectionView}}" CommandParameter="{Binding .}"
                                                             Source="web.png" HeightRequest="60" WidthRequest="60" VerticalOptions="CenterAndExpand" HorizontalOptions="EndAndExpand" />
                                            </StackLayout>
                                        </Frame>
                                    </DataTemplate>
                                </context:SideContextMenuView.ContextTemplate>
                            </context:SideContextMenuView>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
            </StackLayout>
        </ContentPage.Content>
    </ContentPage>
    <ContentPage Title="Orders" Icon="Orders.png" BackgroundColor="#0F2169">
        <ContentPage.Content>
            <StackLayout>

            </StackLayout>
        </ContentPage.Content>
    </ContentPage>
</TabbedPage>`

`namespace AndroidFueledV1.ViewModels
{
    public class DataItemsViewModel : INotifyPropertyChanged
    {
        public DataItemsViewModel()
        {
            LoginCommand = new Command(async () => await Login(), () => !IsBusy);
           
        }

        public int iLoginCount = 0;
        private DataInteraction DIconnection = new DataInteraction();
        public List<DataInteraction.FuelTankClass> DIFTC = new List<DataInteraction.FuelTankClass>();

        public event PropertyChangedEventHandler PropertyChanged;

        private bool _isBusy = false;

        public bool IsBusy
        {
            get { return _isBusy; }
            set
            {
                _isBusy = value;
                OnPropertyChanged();
                LoginCommand.ChangeCanExecute();
            }
        }

       

        private List<DataInteraction.FuelTankClass> _CleanTankList { get; set; } = new List<DataInteraction.FuelTankClass>();

        public List<DataInteraction.FuelTankClass> CleanTankList
        {
            get { return _CleanTankList; }
            set
            {
                _CleanTankList = value;
                OnPropertyChanged();
            }
        }

        private List<DataInteraction.Newsitems> list = new List<DataInteraction.Newsitems>();
        private ObservableCollection<DataInteraction.Newsitems> _CleanList { get; set; } = new ObservableCollection<DataInteraction.Newsitems>();

        public ObservableCollection<DataInteraction.Newsitems> CleanList
        {
            get { return _CleanList; }
            set
            {
                _CleanList = value;
                OnPropertyChanged();
            }
        }

        protected void OnPropertyChanged([CallerMemberName] string name = "")
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));

        private string _sUser = Preferences.Get(nameof(SUser), string.Empty);

        public string SUser
        {
            get { return _sUser; }
            set
            {
                _sUser = value;
                if (RememberMe)
                    Preferences.Set(nameof(SUser), value);
                OnPropertyChanged();
                OnPropertyChanged(nameof(RememberMe));
            }
        }

        private string _sPass = string.Empty;

        public string SPass
        {
            get { return _sPass; }
            set
            {
                _sPass = value;
                OnPropertyChanged();
            }
        }

        private string _sBranch = string.Empty;

        public string SBranch
        {
            get { return _sBranch; }
            set
            {
                _sBranch = value;
                if (SBranch != null)
                    GetTanks();
                OnPropertyChanged();
            }
        }

        private bool _YesConn = true;

        public bool Yesnoconn
        {
            get { return _YesConn; }
            set
            {
                _YesConn = value;
                OnPropertyChanged();
            }
        }

        private List<string> _BranchList { get; set; } = new List<string>();

        public List<string> BranchList
        {
            get { return _BranchList; }
            set
            {
                _BranchList = value;
                OnPropertyChanged();
            }
        }

        public bool RememberMe
        {
            get => Preferences.Get(nameof(RememberMe), false);
            set
            {
                Preferences.Set(nameof(RememberMe), value);
                if (!value)
                {
                    Preferences.Set(nameof(SUser), string.Empty);
                }
                OnPropertyChanged(nameof(RememberMe));
            }
        }

        private ICommand _deleteCommand;

        public ICommand DeleteCommand => _deleteCommand ?? (_deleteCommand = new Command(item =>
        {
            CleanList.Remove(item as DataInteraction.Newsitems);
            //OnPropertyChanged();
        }));

        private ICommand _newsview;

        public ICommand NewsViewCommand => _newsview ?? (_newsview = new Command(async item =>
        {
            DataInteraction.Newsitems news = item as DataInteraction.Newsitems;
            string URL = news.Newslinks;
            try
            {
                Device.OpenUri(new System.Uri(URL));
            }
            catch
            {
                try
                {
                }
                catch
                {
                    await Application.Current.MainPage.DisplayAlert("Nothing Loaded", URL, "OK");
                }
            }
        }));

        public Command LoginCommand { get; }

        private async Task Login()
        {
            CleanList.Clear();
            LSTankName.Clear();
            LSAvgMovement.Clear();
            LSCapacity.Clear();
            LSCurrentAmount.Clear();
            LSRunDryDays.Clear();
            LSProduct.Clear();
            try
            {
                IsBusy = true;
                
                CrossToastPopUp.Current.ShowToastMessage("Loading");
                await Task.Run(() => GetLoginStuff());
            }
            catch { }
            finally
            {
                IsBusy = false;
                
                CrossToastPopUp.Current.ShowToastMessage("Done");
                if (BranchList.Count == 0)
                {
                    await Application.Current.MainPage.DisplayAlert("Login Failure", "Please Check Your Username or Password!", "OK");
                }
                else
                {
                    IsenabledBRANCH = true;
                }
            }
           
        }

        private void GetLoginStuff()
        {
            DataInteraction DIconnection = new DataInteraction();
            DIconnection.DIpassword = SPass;
            DIconnection.DIusername = SUser;
            DIFTC = DIconnection.CreateLogin();
            try
            {
                BranchList.Clear();
            }
            catch { }
            try
            {
                BranchList = DIconnection.DIbranch;
            }
            catch { }
            try
            {
                list = DIconnection.GetNewsitems();
            }
            catch { }
            foreach (DataInteraction.Newsitems news in list)
            {
                if (news.Newsitem != "")
                    try
                    {
                        CleanList.Add(news);
                    }
                    catch { }
            }
        }

        private bool _IsenabledBRANCH = false;

        public bool IsenabledBRANCH
        {
            get { return _IsenabledBRANCH; }
            set
            {
                _IsenabledBRANCH = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSCurrentAmount { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSCurrentAmount
        {
            get { return _LSCurrentAmount; }
            set
            {
                _LSCurrentAmount = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSTankName { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSTankName
        {
            get { return _LSTankName; }
            set
            {
                _LSTankName = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSProduct { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSProduct
        {
            get { return _LSProduct; }
            set
            {
                _LSProduct = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSCapacity { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSCapacity
        {
            get { return _LSCapacity; }
            set
            {
                _LSCapacity = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSAvgMovement { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSAvgMovement
        {
            get { return _LSAvgMovement; }
            set
            {
                _LSAvgMovement = value;
                OnPropertyChanged();
            }
        }

        private ObservableCollection<string> _LSRunDryDays { get; set; } = new ObservableCollection<string>();

        public ObservableCollection<string> LSRunDryDays
        {
            get { return _LSRunDryDays; }
            set
            {
                _LSRunDryDays = value;
                OnPropertyChanged();
            }
        }

        public Command GetTanksCommand { get; }

        private void GetTanks()
        {
            LSTankName.Clear();
            LSAvgMovement.Clear();
            LSCapacity.Clear();
            LSCurrentAmount.Clear();
            LSRunDryDays.Clear();
            LSProduct.Clear();

            try
            {
                List<DataInteraction.FuelTankClass> FTCL = new List<DataInteraction.FuelTankClass>();
                FTCL.Clear();
                foreach (DataInteraction.FuelTankClass FTC in DIFTC)
                {
                    if (FTC.sBranchName == SBranch)
                    {
                        FTCL.Add(FTC);
                    }
                }

                LSTankName.Clear();
                foreach (DataInteraction.FuelTankClass ft in FTCL)
                {
                    LSTankName.Add(ft.sTankName);
                    LSProduct.Add(ft.sTankProduct);
                    LSCapacity.Add(ft.iTankCapacity.ToString());
                    LSCurrentAmount.Add(ft.iTankCurrent.ToString());
                    LSAvgMovement.Add(ft.iAVGmovement.ToString());
                    LSRunDryDays.Add(ft.iDaystoRunDry.ToString());
                    
                }
            }
            catch
            {
                Application.Current.MainPage.DisplayAlert("Nothing Loaded", "No Data Recorded for Last 7 Days.", "OK");
            }
        }
    }
}`

**Comment by stefanvesely** [comment]
Just ignore the elements of the form that can be put in a style sheet, I went through a bunch of debugging that ultimately broke down the code into very simple elements. After breaking everything down and re-breaking it down and simplifying it over and over, it ended up still doing the same things over and over so i removed the normal list view and the collection view still required a tap to show and then i removed the collection view and the listview started working as expected.

**Comment by AndreiMisiukevich** [comment]
doesn't look like this plugin issue
closing for now

**Comment by stefanvesely** [comment]
Hiya, 
I think that the issue comes in when you mix your plugin, with async tasks and activity indicator. 
What I have done now is completely replace your context menu with one i have built from scratch that does everything yours does. 
Now there is no more issues... so it has to do with your code somewhere and I cant find the issue.

Anyway thanks and have a good day.
