### ISSUE TITLE
Problem with SideActionBarCell in Xamarin Forms >= 4.0

### ISSUE THREAD

**Issue by rocktool27** [AndreiMisiukevich/ContextMenu#33]
The swipe works at the beginning, but when you do scroll, templates in SideActionBarCell have errors. This only happens on Android.

I have a RecycleElement Strategy for the list.
![1562170978801](https://user-images.githubusercontent.com/31711135/60608417-0b75ee00-9d85-11e9-871e-67a3dc72eda9.JPEG)

**Comment by AndreiMisiukevich** [comment]
Cells are deprecated 
Use views

**Comment by rocktool27** [comment]
Also in ListView?

Edit: My fault, I didn't see the new code with CollectionView.

**Comment by AndreiMisiukevich** [comment]
@rocktool27 does it work?

**Comment by Zure1** [comment]
I experience the same with the new Views, with Android with X.F >= 4.0. After scrolling. The views sporadically disappear and swipe doesn't work anymore. Didn't make a difference to use RetainElement or RecycleElement.

iOS works fine.

**Comment by AndreiMisiukevich** [comment]
Don't forget to bind your view's width to width of the container (CollectionView or ListView) - Check readme for more info
