### ISSUE TITLE
Enhancement: Get current state of menu

### ISSUE THREAD

**Issue by aubiyko** [AndreiMisiukevich/ContextMenu#35]
There is no property to get current state (opened or closed) of context menu view or cell. Such events do exist, but I think having seperate properties is nice and more convenient to work with.

**Comment by AndreiMisiukevich** [comment]
yeah, they are protected now
```csharp
        protected ScrollDirection CurrentDirection { get; private set; }
        protected ScrollState CurrentState { get; private set; }
```

you can get access in case of inherit class

**Comment by aubiyko** [comment]
CurrentDirection and CurrentState are in "LEGACY CODE" region at BaseContextMenuView. Can I use them safely?

**Comment by AndreiMisiukevich** [comment]
@aubiyko i think yes. But for sure i need to refactor all project, because code quality is super bad
