### ISSUE TITLE
Move To Delete - swipe content visible when cancelled

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/ContextMenu#36]
If I start swipe, and the slide it closed in order to cancel the action, then the underlying content is still visible:
from sample app:
![image](https://user-images.githubusercontent.com/1822976/61460358-debdfb00-a96e-11e9-8741-164cfd19fc3a.png)
here's another snap from another app
![image](https://user-images.githubusercontent.com/1822976/61460423-01501400-a96f-11e9-85f8-b7ccfe338667.png)

**Comment by AndreiMisiukevich** [comment]
play with margins/paddings of bottom content as I did it for my sample :)
