### ISSUE TITLE
Move To Delete - items become stuck [Android]

### ISSUE THREAD

**Issue by InquisitorJax** [AndreiMisiukevich/ContextMenu#37]
Tested on android device api 23
using the sample app.
When I delete a few items, and scroll the listview - some items get into a state where they can only be swiped about 1 or 2 pixels.

**Comment by TzounasA** [comment]
Same problem here. I use ListView. 

Actually i cloned the sample project from here and it has the same issue

**Comment by AndreiMisiukevich** [comment]
Hey guys, sorry for delay.
But i have 6 open source xamarin.forms projects.. extremely little time.

I appreciate any help. Feel free to make PRs

**Comment by AndreiMisiukevich** [comment]
cannot reproduce on latest code (just updated packages)
on API 28 emulator
