### ISSUE TITLE
Is it possible to use SwipeActionContextHolder within a ListView?

### ISSUE THREAD

**Issue by Alexander-Alekseev** [AndreiMisiukevich/ContextMenu#39]
Hi, I'm interesting if it is possible to use SwipeActionContextHolder within a ListView?

I did try your example with CollectionView - it works OK, but for my project I need swipe-to-delete functionality in a ListView. When I tried to implement such functionality I got an uncaught exception:

> System.InvalidCastException
>   Message=Specified cast is not valid.

If it is not possible to use a ListView at all then I just wanna know why :) Or maybe any ideas how I could extend your project?

If it should be possible then you can look at the example code with the error here: https://github.com/Alexander-Alekseev/ContextMenu/blob/list_view_example/ContextMenuSample/ContextMenuSample/Pages/MoveToDeletePage.xaml.

**Comment by AndreiMisiukevich** [comment]
put holder INSIDE ViewCell

**Comment by Alexander-Alekseev** [comment]
Ah, thanks!
