### ISSUE TITLE
iOS: IsAutoCloseEnabled not working

### ISSUE THREAD

**Issue by nielscup** [AndreiMisiukevich/ContextMenu#41]
I have multiple list items and I swipe the 1st item to open the contextMenu. If I then swipe a 2nd item, the 1st item remains open, resulting in 2 items showing contextMenu. 
On Android the 1st item closes as soon as I swipe another item.

Also, iOS does not snap/animate when swiping. It will remain half opened if you let go too soon. Any ideas?
![Screenshot 2019-09-09 at 17 04 43](https://user-images.githubusercontent.com/3483085/64542517-fe94ee00-d323-11e9-92b2-30959a8b3327.png)

**Comment by AndreiMisiukevich** [comment]
Would you like to debug this case?

**Comment by nielscup** [comment]
This problem was caused by our own code: on iOS the list item would swipe vertically as well as horizontally, which is not desired. So we added code to prevent vertical swiping for iOS. This apparently changed the autoclose behaviour. Looking into the vertical swipe issue now...
