### ISSUE TITLE
Swipe feature In left

### ISSUE THREAD

**Issue by RaviKamboj** [AndreiMisiukevich/ContextMenu#43]
Hello Andrei,
Is there any way to make list view item scroll to left as well and add one or two views at left corner . please reply asap.
any help will be really appreciate
Thanks

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/ContextMenu/issues/20#issuecomment-494545639

**Comment by RaviKamboj** [comment]
As per my requirement i have to use it inside List view (Not in Collection View). But whenever i debug it its crashed on Android/iOS both platforms. is there any way to use swipe functionality from left inside List view. Please also mention if it 's possible to use swipe left right in one item. Please reply asap.

**Comment by RaviKamboj** [comment]
Hello Andrei ,
Thanks for previous replies.
As per my requirement i have to use it inside List view (Not in Collection
View). But whenever i debug it its crashed on Android/iOS both platforms.
is there any way to use swipe functionality from left inside List view.
Please also mention if it 's possible to use swipe left right in one item.
Please reply asap.
Regards
Ravi Kamboj

**Comment by AndreiMisiukevich** [comment]
@RaviKamboj of course. Just wrap view with ViewCell if you want to use in inside ListView

**Comment by AndreiMisiukevich** [comment]
left/Right in one item -- unfortunately not for now :(

**Comment by RaviKamboj** [comment]
[
<img width="1254" alt="Screenshot 2019-09-23 at 2 44 34 PM" src="https://user-images.githubusercontent.com/43990283/65414141-b3dda080-de10-11e9-9288-0be867a82c8e.png">
](url)

**Comment by RaviKamboj** [comment]
Have tried as u say but studio showing this error .:(

**Comment by RaviKamboj** [comment]
oh thanks Andrei
following you for left right swipe in both direction .
Thanks again :)
