### ISSUE TITLE
Is it possible "Long press" on an element?

### ISSUE THREAD

**Issue by Gloomv01** [AndreiMisiukevich/ContextMenu#45]
Did it possible "Long press" on an element?
Your ContextMenu it's great component. But I also need a "Long press" on the item, is it possible?
I wont do something on "Long press".

**Comment by AndreiMisiukevich** [comment]
Hi, no, this feature is not supported.

maybe it will help https://alexdunn.org/2017/12/27/xamarin-tip-xamarin-forms-long-press-effect/

**Comment by Gloomv01** [comment]
Thanks, for quick answer.
