### ISSUE TITLE
Combination of ContextMenu's

### ISSUE THREAD

**Issue by sereoja** [AndreiMisiukevich/ContextMenu#46]
Hi Andrei, 
Great job, I really enjoy your work.  
Is it possible to have a combination of Context Menus? Something similar to mail app on ios, a combination of side menu and swipe to delete?
Thx

**Comment by AndreiMisiukevich** [comment]
Hi @sereoja. I thought about such an enhancement. I think we can try at least :)
SwipeGestureRecognizer on iOS and gesture detector on Android

**Comment by AndreiMisiukevich** [comment]
Hi, it won't be implemented. XF introduced own SwipeView
