### ISSUE TITLE
Is it possible to Swipe Action Context Menu View move both ways?

### ISSUE THREAD

**Issue by ThallisonRhanniel** [AndreiMisiukevich/ContextMenu#47]
Hello Andrei.
Great job, I really like this lib.
The function is the same as SwipeActionContextMenuView, but with the ability to swipe both sides and each side performing a different function, just like the ios email application.
Thanks

**Comment by AndreiMisiukevich** [comment]
for now not, but we can consider it

**Comment by AndreiMisiukevich** [comment]
sorry, it won't be implemented. Since XF introduced SwipeVIew
