### ISSUE TITLE
If entry is kept in DataTemplate, for Swipe action, The entire cell scrolls above in iOS and the data entered is not visible.

### ISSUE THREAD

**Issue by ShazimaNaaz** [AndreiMisiukevich/ContextMenu#48]

**Comment by ShazimaNaaz** [comment]
![Screenshot 2019-10-18 at 1 14 41 PM](https://user-images.githubusercontent.com/52919216/67075689-4ae80f00-f1a9-11e9-88bb-751d1730b642.png)


Please find the attachment for reference.

**Comment by AndreiMisiukevich** [comment]
Hi) Hmmm. It doesn't look like this project's issue. That's more XF bug.
So, I suggest resizing page's height on keyboard opening/closing

Here is the renderer https://github.com/AndreiMisiukevich/GalleyFramework/blob/master/GalleyFramework.iOS/Renderers/GalleySuperPageKeyboardRenderer.cs
