### ISSUE TITLE
Previously swiped item is not getting reset on swiping new item in the Listview

### ISSUE THREAD

**Issue by VenkyBalaraju** [AndreiMisiukevich/ContextMenu#5]
I have found one issue while swiping items in the listview, is that if there is one item is already swiped and other item is tried to be swiped then previous ones is not getting reset.
Previously swiped item should be reset when new item is getting selected or swiped.

Can you suggest me how to close or reset previously swiped item in the listview ?

Please check out this screenshot:
https://us.v-cdn.net/5019960/uploads/editor/22/auomq1fnp8bv.png

**Comment by AndreiMisiukevich** [comment]
@VenkyBalaraju Hi
Try it now on my sample, i've implemented logic for managing it "from box".

**Comment by AndreiMisiukevich** [comment]
@VenkyBalaraju if it's ok, it will be included in the next release
