### ISSUE TITLE
SelectionChanged 

### ISSUE THREAD

**Issue by ramziqoura** [AndreiMisiukevich/ContextMenu#52]
Hi
Why SelectionChanged is not working in CollectionView?

<CollectionView x:Name="CollectionView" ItemsSource="{Binding Items}" SelectionMode ="Single" SelectionChanged="OnSelectionChanged" Margin="0, 5, 0, 0" BackgroundColor="White">
</CollectionView >

Thanks

**Comment by AndreiMisiukevich** [comment]
Hi, no idea
I suggest using TapGestureRecognizer for that
