### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by RaviKamboj** [AndreiMisiukevich/ContextMenu#55]
Hello Mate,
first of all, you really developed a great module... really it works very smooth and nice. I have integrated your code in to my project like added BaseActionViewCell.cs files in my project and its working fine. But the problem i am facing right now is that i have to write unit test cases for each .cs file. i have written for all the classes except swipe module(your code). Please help me its urgent .

**Comment by AndreiMisiukevich** [comment]
@RaviKamboj I am not sure that it makes any sense to write UNIT tests for UI part... it's super strange.

I don't know what do you want to test there by Unit tests.
