### ISSUE TITLE
How to close context menu after invoking a command?

### ISSUE THREAD

**Issue by JPAhnen** [AndreiMisiukevich/ContextMenu#57]
I attached a very simple command which just changes a bool value of the list item and updates it in the database. 
I want to close the context menu when the command has finished. How can I do this?

This is the command that is called:
```
ToggeActiveStateCommand = new Command(async (item) =>
{
    var i = (MyViewModel)item;
    i.ToggleDeactivation();
    await i.SaveChanges();
});
```
and this is how the code is invoked:
```
<Button Text="Change" Command="{Binding Path=BindingContext.ToggeActiveStateCommand, Source={x:Reference Name=myList}}" CommandParameter="{Binding .}"></Button>
```

AutoClose is enabled:
```
<context:SideContextMenuView IsAutoCloseEnabled="true">
```

Everything works, but how can I close the context menu?
Thanks!

**Comment by AndreiMisiukevich** [comment]
Bind to ForceCloseCommand and invoke it for closing menu

**Comment by raghulvaikundam** [comment]
`Bind to ForceCloseCommand and invoke it for closing menu` this is not working for me. Probably I might be missing something. 
Following is the description of my effort for closing the menu
I have defined a variable called forceClose of type ICommand and bound that variable to a ForceCloseCommand attribute. I invoked it as forceClose.Excecute(this)

**Comment by AndreiMisiukevich** [comment]
> `Bind to ForceCloseCommand and invoke it for closing menu` this is not working for me. Probably I might be missing something.
> Following is the description of my effort for closing the menu
> I have defined a variable called forceClose of type ICommand and bound that variable to a ForceCloseCommand attribute. I invoked it as forceClose.Excecute(this)

In Xaml **ForceCloseCommand="{Binding ForceCloseCommand}"**

In code

**public ICommand ForceCloseCommand { get; set; }**

And invoke it whenever you want

**Comment by raghulvaikundam** [comment]
> > `Bind to ForceCloseCommand and invoke it for closing menu` this is not working for me. Probably I might be missing something.
> > Following is the description of my effort for closing the menu
> > I have defined a variable called forceClose of type ICommand and bound that variable to a ForceCloseCommand attribute. I invoked it as forceClose.Excecute(this)
> 
> In Xaml **ForceCloseCommand="{Binding ForceCloseCommand}"**
> 
> In code
> 
> **public ICommand ForceCloseCommand { get; set; }**
> 
> And invoke it whenever you want

In the above piece of code, ForceCloseCommand property will not have any implementation in my ViewModel. My question is how will this command will close the Context. It would be great, if you explain with little more details

**Comment by AndreiMisiukevich** [comment]
> > > `Bind to ForceCloseCommand and invoke it for closing menu` this is not working for me. Probably I might be missing something.
> > > Following is the description of my effort for closing the menu
> > > I have defined a variable called forceClose of type ICommand and bound that variable to a ForceCloseCommand attribute. I invoked it as forceClose.Excecute(this)
> > 
> > 
> > In Xaml **ForceCloseCommand="{Binding ForceCloseCommand}"**
> > In code
> > **public ICommand ForceCloseCommand { get; set; }**
> > And invoke it whenever you want
> 
> In the above piece of code, ForceCloseCommand property will not have any implementation in my ViewModel. My question is how will this command will close the Context. It would be great, if you explain with little more details

Did you try?
ForceCloseCommand is OneWayToSource bindable property. If you bind it, you will see that it has values

ForceCloseCommand.Execute(null);

**Comment by raghulvaikundam** [comment]
Thanks It was working fine.
