### ISSUE TITLE
Do we get any callback while performing swipe using SideContextMenuView which is present inside the CollectionView?

### ISSUE THREAD

**Issue by raghulvaikundam** [AndreiMisiukevich/ContextMenu#61]
Upon swiping, I need to execute some business logic. How do we achieve that

**Comment by AndreiMisiukevich** [comment]
public event Action<BaseContextMenuView> ContextMenuOpened;
        public event Action<BaseContextMenuView> ContextMenuClosed;
        public event Action<BaseContextMenuView> TouchStarted;
        public event Action<BaseContextMenuView> TouchEnded;

**Comment by AndreiMisiukevich** [comment]
> ```
>     public event Action<BaseContextMenuView> ContextMenuOpened;
>     public event Action<BaseContextMenuView> ContextMenuClosed;
>     public event Action<BaseContextMenuView> TouchStarted;
>     public event Action<BaseContextMenuView> TouchEnded;
> ```

There are several events
