### ISSUE TITLE
ScrollUp trigger RefreshView to Refreshing

### ISSUE THREAD

**Issue by housecode** [AndreiMisiukevich/ContextMenu#63]
When wrapping `CollectionView` in example page (e.g: `SideMenuPage` or any example page) with `Xamarin.Forms.RefreshView`, `IsRefreshing` property value set to true.

```
<RefreshView>
    <CollectionView x:Name="CollectionView"
                    ItemsSource="{Binding Items}"
                    Margin="0, 5, 0, 0"
                    BackgroundColor="White">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <context:SideContextMenuView IsAutoCloseEnabled="true"
                                             ForceCloseCommand="{Binding ForceCloseCommand}">
....
                </context:SideContextMenuView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</RefreshView>
```

## Step to Reproduce:
1. Update `Xamarin.Forms` to latest (4.7.0.968)
2. Change the example and wrap the `CollectionView` with `RefreshView`
3. Don't scroll down/up, then swipe one of displayed item
4. Don't click any context menu
5. Scroll up and refreshing icon appears

## Affected platform:
Android

## Screen Recording:
https://drive.google.com/file/d/1-I2fl0UgpC1wAPifLjoNljX4zRqsn5Sy/view?usp=sharing

**Comment by AndreiMisiukevich** [comment]
Hi,
Weird bug.

Can you reproduce this bug with XF SwipeView ?

**Comment by housecode** [comment]
Nope, I can't reproduce with SwipeView
