### ISSUE TITLE
Android: ForceCloseCommand does not work if it is called from a TapCommand within the ContextTemplate with Animation active

### ISSUE THREAD

**Issue by acuntex** [AndreiMisiukevich/ContextMenu#64]
If you call ForceCloseCommand on Android to close the ContextMenu after/before you execute a command then it will be open again.

e.g.
```
        <context:SideContextMenuView.ContextTemplate>
            <DataTemplate>
                <StackLayout BackgroundColor="Red"
                             Padding="50,0,50,0"
                             touchEffect:TouchEff.NativeAnimation="True"
                             touchEffect:TouchEff.Command="{Binding DeleteCommand, Source={RelativeSource AncestorType={x:Type infrastructure:BasePageModel}}}"
                             touchEffect:TouchEff.CommandParameter="{Binding}">
                    <Label Text="{extensions:Translate Delete}" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" VerticalTextAlignment="Center" HorizontalTextAlignment="Center"/>
                </StackLayout>
            </DataTemplate>
        </context:SideContextMenuView.ContextTemplate>  
    </context:SideContextMenuView>
```
First line of the DeleteCommand is:
```
obj.ForceCloseCommand?.Execute(null);
```
It also happens with a regular GestureRecognizer, so it's not related to TouchEff.

Somehow, the ForceCloseCommand gets called, it also executes the ScrollTo(0.0,0.0,animated), but somehow after that, TouchEnded reopens it again.

The only way to make it work is to call it the following way:
```
obj.ForceCloseCommand?.Execute(false);
```

This way TouchEnded does not open it again.

**Comment by AndreiMisiukevich** [comment]
Weird. Can you build a small sample?

**Comment by acuntex** [comment]
I've created an isolated sample here:
https://github.com/acuntex/ContextMenuBug_ForceCloseCommand

On iOS it works fine.
On Android it does not work if Animations for Closing are enabled.

Sorry for the hacky solution, it's a bit hard without proper MVVM-Framework ;-)

**Comment by AndreiMisiukevich** [comment]
Cannot promise that I will take a look soon.
But feel free to debug this library and make PR if you wish)

**Comment by AndreiMisiukevich** [comment]
Closing stale bug-report
Please let me know if this issue still occurs (pushed a new version a day ago)
