### ISSUE TITLE
Cant get it to work properly, see video

### ISSUE THREAD

**Issue by nielscup** [AndreiMisiukevich/ContextMenu#67]
I copied the same code from the sample but it does not work as expected, see video:
https://user-images.githubusercontent.com/3483085/122004434-b33f2780-cdb4-11eb-9e21-1a6d91c6c272.mov

Any ideas what can be the problem?

**Comment by nielscup** [comment]
My bad: I forgot ContextMenuViewRenderer.Preserve(); Works fine now!

**Comment by AndreiMisiukevich** [comment]
Great :)
