### ISSUE TITLE
SideContextMenuView: auto close when tapped

### ISSUE THREAD

**Issue by nielscup** [AndreiMisiukevich/ContextMenu#69]
How do I auto close the context menu after tapping a context menu item? In the example it remains open when tapped which is not desired.

**Comment by AndreiMisiukevich** [comment]
Hi, you should call ForceClose or ForceCloseCommand

**Comment by AndreiMisiukevich** [comment]
e.g.

SideContextMenuView?.LastOpenedView?.ForceClose();

**Comment by nielscup** [comment]
Thanks for your quick response!! How do I reference the SideContextMenuView? Via the TapGesture?

**Comment by AndreiMisiukevich** [comment]
```<SideContextMenuView x:Name="context" /> ```

```<TapGestureRecognizer Command="{Binding ForceCloseCommand, Source={x:Reference context}}"```

Smth like this
