### ISSUE TITLE
Isautoclosingenabled not working when scrolling in iOS 

### ISSUE THREAD

**Issue by brettnguyen** [AndreiMisiukevich/ContextMenu#73]
The auto closing for iOS doesn’t work when scrolling.

**Comment by AndreiMisiukevich** [comment]
Yes, you should call "close" yourself)
`Isautoclosingenabled` means that the menu is closing automatically after opening it

**Comment by brettnguyen** [comment]
Okay. So how do I close the menu if the contextview is inside a data template? For example I want the scrolling from a collectionview to close the menu how would that work?

**Comment by AndreiMisiukevich** [comment]
Subscribe CollectionView scrolled event, and inside that handler just call 

SideContextMenuView.LastOpenedView.ForceClose();
