### ISSUE TITLE
How do I got about calling the “close” menu command/action outside of the data template?

### ISSUE THREAD

**Issue by brettnguyen** [AndreiMisiukevich/ContextMenu#74]
For example how would I call close context menu with a collectionview when the context menu is inside the data template? If this is not possible close this issue.

**Comment by AndreiMisiukevich** [comment]
@brettnguyen 

Subscribe CollectionView scrolled event, and inside that handler just call

SideContextMenuView.LastOpenedView.ForceClose();

**Comment by brettnguyen** [comment]
Works thank you. The animation to close it is a bit slower but that could just be the iOS emulator I’m using
