### ISSUE TITLE
Are we able to disallow a user from swiping?

### ISSUE THREAD

**Issue by JustinJWyatt** [AndreiMisiukevich/ContextMenu#75]
I need to be able to set on the context item view whether I want the user to be able to swipe based on a condition.

**Comment by AndreiMisiukevich** [comment]
can you try to set IsEnabled=False? (to entire context menu view)

**Comment by JustinJWyatt** [comment]
> can you try to set IsEnabled=False? (to entire context menu view)

Yes I have tried setting `ExtendedSideContextMenuView.IsEnabled` to `False` but this actually disables my `TapGestureRecognizer` within my `SideContextMenu.View`. I don't want my tap gesture disabled. I want it to only prevent the user from swiping the one item based on a condition for that one item in collection view.

**Comment by AndreiMisiukevich** [comment]
Well, try to set IsVisible=False for Context view then

**Comment by AndreiMisiukevich** [comment]
But honestly speaking I am not sure that this is possible with the current implementation

**Comment by AndreiMisiukevich** [comment]
@JustinJWyatt
closing it due to inactivity
