### ISSUE TITLE
Tap event in MoveToActionCell

### ISSUE THREAD

**Issue by alexmartinezm** [AndreiMisiukevich/ContextMenu#8]
Hi there,

I am trying to tap a MoveToActionCell item, with no success.

Is there any way to achieve this? I have tried to set InputTransparent to true, but it seems to not work properly.

Regards,
AMM.

**Comment by AndreiMisiukevich** [comment]
@alexmartinezm probably, scrollView swallows touches.
Do tapGestureRecognizers work?

**Comment by alexmartinezm** [comment]
Where should I create TapGestures? I have tried to create it in the ContentProperty of MoveToActionCell with no success because it disables the swipe action.

**Comment by AndreiMisiukevich** [comment]
@alexmartinezm that's strange
Need to check it
Because tapGesture should't disable scrollView...

**Comment by alexmartinezm** [comment]
Ok! I keep trying to find out what's going on.

**Comment by AndreiMisiukevich** [comment]
@alexmartinezm thanks so much for you contribution :)

**Comment by alexmartinezm** [comment]
Alright, it was my bad. I was not setting the gesture in the correct place.

You can close this issue. Thank you!

**Comment by pkozak2** [comment]
Where I have to add tapGestureRecognizer to allow tapping list elements?

**Comment by AndreiMisiukevich** [comment]
@pkozak2 I presume, to your contentview

**Comment by pkozak2** [comment]
True, I forgot that I inserted inputTransparent arrtibute to contentView. Now its working fine

**Comment by AndreiMisiukevich** [comment]
@AndreiMisiukevich enjoy :)
