### ISSUE TITLE
Doesn't work on iOS | Multi selection close issue | RTL support issue

### ISSUE THREAD

**Issue by IgorPopov56** [AndreiMisiukevich/ContextMenu#9]
Hi. First of all thanks for the plugin =) I collected few problems I was facing. If something that I described is unclear please write.

1) SideActionBarSamplePage code doesn't work on iOS platform when I'm using using Nuget package.
https://streamable.com/yzlor
If I'm launching the sample project from GitHub, everything works.

2) First move - swiping few ListView items, second move - try to swap another item. As you can see in video, only one item returns to previous state. Other swiped items remain shifted.
https://streamable.com/4xdcd

3) When set "FlowDirection=RightToLeft", swipe functional become broken:
https://streamable.com/k0q4n

**Comment by AndreiMisiukevich** [comment]
@IgorPopov56 Hi, thank you very much for feedback

1) Call ```ContextMenuScrollViewRenderer.Initialize()``` in AppDelagate for **iOS** for preserving linking. (I updated Readme :) )

**Comment by AndreiMisiukevich** [comment]
2) Wow.. good case :) really i didn't design the plugin fro such cases. Need to investigate, how to fix it WITHOUT memory leaks :) I am not keen to store in memory all cells.

**Comment by AndreiMisiukevich** [comment]
3) Seems to be Xamarin.Forms issue..

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich About point 3 ("FlowDirection=RightToLeft"). I found out WHY it happens. ViewStack (of type StackLayout), than contains ContentView and ContextView, is changing the order of elements. That's why Context is left view, Content - right. Scroll logic doesn't change from the value of the variable FlowDirection.
So when "ForceCloseContextMenu" method executes ("await view.ScrollToAsync(0, 0, animated);"), ListViewItem from UI point of view becoming like this:
http://prntscr.com/lt44eb

**Comment by AndreiMisiukevich** [comment]
@IgorPopov56 Are there any ideas how to fix it?)

**Comment by IgorPopov56** [comment]
@AndreiMisiukevich For now the only idea is to add support of RTL in code (re-create all the logic for RTL, inserting the correct values in methods (for example, ScrollTo).

**Comment by AndreiMisiukevich** [comment]
RTL: i'm not keen to support RTL for this nuget.

Everybody should feel free to contribute it :)
